currencies = [
    (u'ALL', u'Albanian Lek'),
    (u'DZD', u'Algerian Dinar'),
    (u'XAL', u'Aluminium Ounces'),
    (u'ARS', u'Argentine Peso'),
    (u'AWG', u'Aruba Florin'),
    (u'AUD', u'Australian Dollar'),
    (u'BSD', u'Bahamian Dollar'),
    (u'BHD', u'Bahraini Dinar'),
    (u'BDT', u'Bangladesh Taka'),
    (u'BBD', u'Barbados Dollar'),
    (u'BYR', u'Belarus Ruble'),
    (u'BZD', u'Belize Dollar'),
    (u'BMD', u'Bermuda Dollar'),
    (u'BTN', u'Bhutan Ngultrum'),
    (u'BOB', u'Bolivian Boliviano'),
    (u'BWP', u'Botswana Pula'),
    (u'BRL', u'Brazilian Real'),
    (u'GBP', u'British Pound'),
    (u'BND', u'Brunei Dollar'),
    (u'BGN', u'Bulgarian Lev'),
    (u'BIF', u'Burundi Franc'),
    (u'KHR', u'Cambodia Riel'),
    (u'CAD', u'Canadian Dollar'),
    (u'CVE', u'Cape Verde Escudo'),
    (u'KYD', u'Cayman Islands Dollar'),
    (u'XOF', u'CFA Franc (BCEAO)'),
    (u'XAF', u'CFA Franc (BEAC)'),
    (u'CLP', u'Chilean Peso'),
    (u'CNY', u'Chinese Yuan'),
    (u'COP', u'Colombian Peso'),
    (u'KMF', u'Comoros Franc'),
    (u'XCP', u'Copper Pounds'),
    (u'CRC', u'Costa Rica Colon'),
    (u'HRK', u'Croatian Kuna'),
    (u'CUP', u'Cuban Peso'),
    (u'CYP', u'Cyprus Pound'),
    (u'CZK', u'Czech Koruna'),
    (u'DKK', u'Danish Krone'),
    (u'DJF', u'Dijibouti Franc'),
    (u'DOP', u'Dominican Peso'),
    (u'XCD', u'East Caribbean Dollar'),
    (u'ECS', u'Ecuador Sucre'),
    (u'EGP', u'Egyptian Pound'),
    (u'SVC', u'El Salvador Colon'),
    (u'ERN', u'Eritrea Nakfa'),
    (u'EEK', u'Estonian Kroon'),
    (u'ETB', u'Ethiopian Birr'),
    (u'EUR', u'Euro'),
    (u'FKP', u'Falkland Islands Pound'),
    (u'FJD', u'Fiji Dollar'),
    (u'GMD', u'Gambian Dalasi'),
    (u'GHC', u'Ghanian Cedi'),
    (u'GIP', u'Gibraltar Pound'),
    (u'XAU', u'Gold Ounces'),
    (u'GTQ', u'Guatemala Quetzal'),
    (u'GNF', u'Guinea Franc'),
    (u'GYD', u'Guyana Dollar'),
    (u'HTG', u'Haiti Gourde'),
    (u'HNL', u'Honduras Lempira'),
    (u'HKD', u'Hong Kong Dollar'),
    (u'HUF', u'Hungarian Forint'),
    (u'ISK', u'Iceland Krona'),
    (u'INR', u'Indian Rupee'),
    (u'IDR', u'Indonesian Rupiah'),
    (u'IRR', u'Iran Rial'),
    (u'IQD', u'Iraqi Dinar'),
    (u'ILS', u'Israeli Shekel'),
    (u'JMD', u'Jamaican Dollar'),
    (u'JPY', u'Japanese Yen'),
    (u'JOD', u'Jordanian Dinar'),
    (u'KZT', u'Kazakhstan Tenge'),
    (u'KES', u'Kenyan Shilling'),
    (u'KRW', u'Korean Won'),
    (u'KWD', u'Kuwaiti Dinar'),
    (u'LAK', u'Lao Kip'),
    (u'LVL', u'Latvian Lat'),
    (u'LBP', u'Lebanese Pound'),
    (u'LSL', u'Lesotho Loti'),
    (u'LRD', u'Liberian Dollar'),
    (u'LYD', u'Libyan Dinar'),
    (u'LTL', u'Lithuanian Lita'),
    (u'MOP', u'Macau Pataca'),
    (u'MKD', u'Macedonian Denar'),
    (u'MWK', u'Malawi Kwacha'),
    (u'MYR', u'Malaysian Ringgit'),
    (u'MVR', u'Maldives Rufiyaa'),
    (u'MTL', u'Maltese Lira'),
    (u'MRO', u'Mauritania Ougulya'),
    (u'MUR', u'Mauritius Rupee'),
    (u'MXN', u'Mexican Peso'),
    (u'MDL', u'Moldovan Leu'),
    (u'MNT', u'Mongolian Tugrik'),
    (u'MAD', u'Moroccan Dirham'),
    (u'MMK', u'Myanmar Kyat'),
    (u'NAD', u'Namibian Dollar'),
    (u'NPR', u'Nepalese Rupee'),
    (u'ANG', u'Neth Antilles Guilder'),
    (u'TRY', u'New Turkish Lira'),
    (u'NZD', u'New Zealand Dollar'),
    (u'NIO', u'Nicaragua Cordoba'),
    (u'NGN', u'Nigerian Naira'),
    (u'KPW', u'North Korean Won'),
    (u'NOK', u'Norwegian Krone'),
    (u'OMR', u'Omani Rial'),
    (u'XPF', u'Pacific Franc'),
    (u'PKR', u'Pakistani Rupee'),
    (u'XPD', u'Palladium Ounces'),
    (u'PAB', u'Panama Balboa'),
    (u'PGK', u'Papua New Guinea Kina'),
    (u'PYG', u'Paraguayan Guarani'),
    (u'PEN', u'Peruvian Nuevo Sol'),
    (u'PHP', u'Philippine Peso'),
    (u'XPT', u'Platinum Ounces'),
    (u'PLN', u'Polish Zloty'),
    (u'QAR', u'Qatar Rial'),
    (u'RON', u'Romanian New Leu'),
    (u'RUB', u'Russian Rouble'),
    (u'RWF', u'Rwanda Franc'),
    (u'WST', u'Samoa Tala'),
    (u'STD', u'Sao Tome Dobra'),
    (u'SAR', u'Saudi Arabian Riyal'),
    (u'SCR', u'Seychelles Rupee'),
    (u'SLL', u'Sierra Leone Leone'),
    (u'XAG', u'Silver Ounces'),
    (u'SGD', u'Singapore Dollar'),
    (u'SKK', u'Slovak Koruna'),
    (u'SIT', u'Slovenian Tolar'),
    (u'SBD', u'Solomon Islands Dollar'),
    (u'SOS', u'Somali Shilling'),
    (u'ZAR', u'South African Rand'),
    (u'LKR', u'Sri Lanka Rupee'),
    (u'SHP', u'St Helena Pound'),
    (u'SDD', u'Sudanese Dinar'),
    (u'SZL', u'Swaziland Lilageni'),
    (u'SEK', u'Swedish Krona'),
    (u'CHF', u'Swiss Franc'),
    (u'SYP', u'Syrian Pound'),
    (u'TWD', u'Taiwan Dollar'),
    (u'TZS', u'Tanzanian Shilling'),
    (u'THB', u'Thai Baht'),
    (u'TOP', u"Tonga Pa'anga"),
    (u'TTD', u'Trinidad&Tobago; Dollar'),
    (u'TND', u'Tunisian Dinar'),
    (u'USD', u'U.S. Dollar'),
    (u'AED', u'UAE Dirham'),
    (u'UGX', u'Ugandan Shilling'),
    (u'UAH', u'Ukraine Hryvnia'),
    (u'UYU', u'Uruguayan New Peso'),
    (u'VUV', u'Vanuatu Vatu'),
    (u'VEB', u'Venezuelan Bolivar'),
    (u'VND', u'Vietnam Dong'),
    (u'YER', u'Yemen Riyal'),
    (u'ZMK', u'Zambian Kwacha'),
    (u'ZWD', u'Zimbabwe Dollar')]

currencyNames = dict(currencies)
